import { useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import type { SymptomEvent, TranscriptEntry } from '../contexts/SessionContext';

interface NotesLocationState {
  transcript: TranscriptEntry[];
  visualLogs: SymptomEvent[];
  sessionId?: string;
}

/**
 * Post-call Notes page that displays AI-generated SOAP notes
 * combining the audio transcript and visual symptom logs.
 */
export function Notes() {
  const location = useLocation();
  const navigate = useNavigate();
  const state = location.state as NotesLocationState | null;
  
  const [notes, setNotes] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [source, setSource] = useState<string>('');

  useEffect(() => {
    if (!state) {
      setError('No visit data provided. Please complete a call first.');
      setLoading(false);
      return;
    }

    const generateNotes = async () => {
      try {
        setLoading(true);
        setError(null);
        
        // Extract text from transcript entries
        const transcriptTexts = state.transcript?.map(t => t.text) || [];
        
        const response = await fetch('/api/generate-notes', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            transcript: transcriptTexts,
            visualLogs: state.visualLogs || [],
          }),
        });
        
        if (!response.ok) {
          throw new Error('Failed to generate notes');
        }
        
        const data = await response.json();
        setNotes(data.notes);
        setSource(data.source || 'unknown');
      } catch (err: any) {
        console.error('Failed to generate notes:', err);
        setError(err.message || 'Failed to generate notes');
      } finally {
        setLoading(false);
      }
    };

    generateNotes();
  }, [state]);

  // Simple markdown-like rendering
  const renderMarkdown = (text: string) => {
    const lines = text.split('\n');
    const elements: JSX.Element[] = [];
    
    lines.forEach((line, i) => {
      if (line.startsWith('# ')) {
        elements.push(<h1 key={i} className="notes-h1">{line.slice(2)}</h1>);
      } else if (line.startsWith('## ')) {
        elements.push(<h2 key={i} className="notes-h2">{line.slice(3)}</h2>);
      } else if (line.startsWith('### ')) {
        elements.push(<h3 key={i} className="notes-h3">{line.slice(4)}</h3>);
      } else if (line.startsWith('**') && line.endsWith('**')) {
        elements.push(<p key={i} className="notes-bold">{line.slice(2, -2)}</p>);
      } else if (line.startsWith('- ')) {
        elements.push(<li key={i} className="notes-li">{line.slice(2)}</li>);
      } else if (line.match(/^\d+\. /)) {
        elements.push(<li key={i} className="notes-li-num">{line.replace(/^\d+\. /, '')}</li>);
      } else if (line.startsWith('---')) {
        elements.push(<hr key={i} className="notes-hr" />);
      } else if (line.startsWith('*') && line.endsWith('*')) {
        elements.push(<p key={i} className="notes-italic">{line.slice(1, -1)}</p>);
      } else if (line.trim()) {
        elements.push(<p key={i} className="notes-p">{line}</p>);
      } else {
        elements.push(<br key={i} />);
      }
    });
    
    return elements;
  };

  if (loading) {
    return (
      <div className="notes-container">
        <div className="notes-loading">
          <div className="notes-spinner"></div>
          <h2>Generating Medical Notes...</h2>
          <p>Our AI is analyzing the transcript and visual observations</p>
        </div>
        <style>{notesStyles}</style>
      </div>
    );
  }

  if (error) {
    return (
      <div className="notes-container">
        <div className="notes-error">
          <h2>Unable to Generate Notes</h2>
          <p>{error}</p>
          <button onClick={() => navigate('/')}>
            Return to Home
          </button>
        </div>
        <style>{notesStyles}</style>
      </div>
    );
  }

  return (
    <div className="notes-container">
      <div className="notes-content">
        <header className="notes-header">
          <h1>📋 Medical Visit Notes</h1>
          <div className="notes-meta">
            {state?.sessionId && (
              <span className="notes-session">Session: {state.sessionId.slice(0, 12)}...</span>
            )}
            <span className="notes-source">Generated by: {source === 'gemini' ? 'Gemini AI' : 'Demo Mode'}</span>
          </div>
        </header>
        
        <div className="notes-stats">
          <div className="stat-item">
            <span className="stat-value">{state?.transcript?.length || 0}</span>
            <span className="stat-label">Transcript Entries</span>
          </div>
          <div className="stat-item">
            <span className="stat-value">{state?.visualLogs?.length || 0}</span>
            <span className="stat-label">Visual Observations</span>
          </div>
        </div>

        <div className="notes-body">
          {notes && renderMarkdown(notes)}
        </div>

        <div className="notes-actions">
          <button 
            className="notes-button primary"
            onClick={() => {
              navigator.clipboard.writeText(notes || '');
              alert('Notes copied to clipboard!');
            }}
          >
            📋 Copy Notes
          </button>
          <button 
            className="notes-button secondary"
            onClick={() => {
              const blob = new Blob([notes || ''], { type: 'text/markdown' });
              const url = URL.createObjectURL(blob);
              const a = document.createElement('a');
              a.href = url;
              a.download = `medical-notes-${Date.now()}.md`;
              a.click();
              URL.revokeObjectURL(url);
            }}
          >
            💾 Download
          </button>
          <button 
            className="notes-button secondary"
            onClick={() => navigate('/')}
          >
            🏠 New Visit
          </button>
        </div>

        <footer className="notes-footer">
          <p>
            These notes are AI-generated for documentation purposes. 
            Always review and verify clinical accuracy before use.
          </p>
        </footer>
      </div>
      <style>{notesStyles}</style>
    </div>
  );
}

const notesStyles = `
  .notes-container {
    min-height: 100vh;
    background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
    padding: 40px 20px;
    display: flex;
    justify-content: center;
    align-items: flex-start;
  }

  .notes-content {
    max-width: 900px;
    width: 100%;
    background: rgba(255, 255, 255, 0.98);
    border-radius: 20px;
    padding: 48px;
    box-shadow: 0 25px 80px rgba(0, 0, 0, 0.4);
  }

  .notes-header {
    text-align: center;
    margin-bottom: 32px;
    padding-bottom: 24px;
    border-bottom: 2px solid #e8e8e8;
  }

  .notes-header h1 {
    margin: 0 0 12px 0;
    font-size: 32px;
    color: #1a1a2e;
    font-weight: 700;
  }

  .notes-meta {
    display: flex;
    justify-content: center;
    gap: 20px;
    font-size: 13px;
    color: #666;
  }

  .notes-session {
    background: #f0f0f0;
    padding: 4px 12px;
    border-radius: 12px;
    font-family: monospace;
  }

  .notes-source {
    background: #e8f4ff;
    color: #0066cc;
    padding: 4px 12px;
    border-radius: 12px;
  }

  .notes-stats {
    display: flex;
    justify-content: center;
    gap: 40px;
    margin-bottom: 32px;
  }

  .stat-item {
    text-align: center;
  }

  .stat-value {
    display: block;
    font-size: 36px;
    font-weight: 700;
    color: #0f3460;
  }

  .stat-label {
    font-size: 12px;
    color: #888;
    text-transform: uppercase;
    letter-spacing: 1px;
  }

  .notes-body {
    line-height: 1.8;
    color: #333;
  }

  .notes-h1 {
    font-size: 28px;
    color: #1a1a2e;
    margin: 32px 0 16px 0;
    padding-bottom: 8px;
    border-bottom: 3px solid #0f3460;
  }

  .notes-h2 {
    font-size: 22px;
    color: #0f3460;
    margin: 28px 0 12px 0;
    padding-bottom: 6px;
    border-bottom: 2px solid #e8e8e8;
  }

  .notes-h3 {
    font-size: 18px;
    color: #16213e;
    margin: 20px 0 10px 0;
  }

  .notes-p {
    margin: 10px 0;
    font-size: 15px;
  }

  .notes-bold {
    font-weight: 700;
    color: #1a1a2e;
    margin: 16px 0 8px 0;
  }

  .notes-italic {
    font-style: italic;
    color: #666;
    font-size: 13px;
  }

  .notes-li, .notes-li-num {
    margin: 6px 0 6px 24px;
    font-size: 15px;
  }

  .notes-hr {
    border: none;
    border-top: 1px solid #ddd;
    margin: 24px 0;
  }

  .notes-actions {
    display: flex;
    justify-content: center;
    gap: 16px;
    margin-top: 40px;
    padding-top: 24px;
    border-top: 1px solid #e8e8e8;
  }

  .notes-button {
    padding: 12px 24px;
    border: none;
    border-radius: 12px;
    font-size: 14px;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.2s;
  }

  .notes-button.primary {
    background: linear-gradient(135deg, #0f3460, #16213e);
    color: white;
  }

  .notes-button.primary:hover {
    transform: translateY(-2px);
    box-shadow: 0 6px 20px rgba(15, 52, 96, 0.4);
  }

  .notes-button.secondary {
    background: #f5f5f5;
    color: #333;
  }

  .notes-button.secondary:hover {
    background: #e8e8e8;
  }

  .notes-footer {
    margin-top: 32px;
    text-align: center;
    color: #888;
    font-size: 12px;
    padding: 16px;
    background: #fafafa;
    border-radius: 12px;
  }

  .notes-loading, .notes-error {
    text-align: center;
    padding: 80px 40px;
    background: white;
    border-radius: 20px;
    max-width: 500px;
  }

  .notes-spinner {
    width: 50px;
    height: 50px;
    border: 4px solid #e8e8e8;
    border-top: 4px solid #0f3460;
    border-radius: 50%;
    animation: spin 1s linear infinite;
    margin: 0 auto 24px;
  }

  @keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }

  .notes-loading h2, .notes-error h2 {
    color: #1a1a2e;
    margin-bottom: 12px;
  }

  .notes-loading p, .notes-error p {
    color: #666;
  }

  .notes-error h2 {
    color: #c0392b;
  }

  .notes-error button {
    margin-top: 24px;
    padding: 12px 32px;
    background: #0f3460;
    color: white;
    border: none;
    border-radius: 8px;
    font-size: 14px;
    cursor: pointer;
  }
`;
